version: '3.8'

services:
  muraena:
    build: .
    container_name: muraena
    expose:
      - "80"
      - "443"
    volumes:
      - ./config:/app/config
      - ./static:/app/static
      - /etc/letsencrypt:/etc/letsencrypt:ro
    environment:
      - TZ=UTC
    restart: unless-stopped
    networks:
      - muraena_net

  redis:
    image: redis:alpine
    container_name: muraena-redis
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - muraena_net

networks:
  muraena_net:
    driver: bridge

volumes:
  redis_data: