version: '3'

services:
  muraena:
    build: .
    container_name: muraena
    ports:
      - "443:443"
    volumes:
      - ./config:/app/config
      - ./static:/app/static
      - ./log:/app/log
      - ./certs:/app/certs
    environment:
      - TZ=UTC
      - CONFIG_FILE=/app/config/local-ssl.toml
    restart: unless-stopped
    networks:
      - muraena_net
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: muraena-redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - muraena_net

networks:
  muraena_net:
    driver: bridge

volumes:
  redis_data:
    driver: local